### ISSUE TITLE
Error thrown in internal/fs/utils.js

### ISSUE THREAD

**Issue by justinshaw** [LukeGarrigan/git-scrum#3]
Saw your comment on `git standup` and had to try this out! I'm encountering an issue, but it's not clear whether or not it's my environment or `git-scrum`. If I run `git-scrum` in _any_ directory (single repo, or parent directory to multiple repos), I get the following:

```
internal/fs/utils.js:298
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/path/to/some/random/file'
    at Object.lstatSync (fs.js:1033:3)
    at /Users/justin/.asdf/installs/nodejs/14.7.0/.npm/lib/node_modules/git-scrum/index.js:11:40
    at Array.filter (<anonymous>)
    at Object.<anonymous> (/Users/justin/.asdf/installs/nodejs/14.7.0/.npm/lib/node_modules/git-scrum/index.js:11:25)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/path/to/some/random/file'
}
```

Note that the `/path/to/some/random/file` file seems to always be a dotfile. That's the only pattern I noticed.

**Comment by LukeGarrigan** [comment]
Hi Justin thank you for raising this, I'm a little confused as I'm struggling to replicate this:
1. What OS do you use? 
2. Does the file that it's failing to open contain `\\.git\\logs\\refs\\heads` or is it in the directory where you're running the script, i.e have a file in that current directory it doesn't like?

Cheers mate

**Comment by LukeGarrigan** [comment]
Hi mate, I've updated the package.

run `npm install git-scrum -g` 

Hopefully, it should fix it or at least point us in the right direction, if you were using anything other than windows I'm pretty sure it wouldn't have worked.

**Comment by justinshaw** [comment]
Hey there! Answering your original questions:
- macOS 10.15.7
- Yes the directories I tried contain a `.git` directory, and it does contain what you'd expect

I updated and re-ran, there's no error output! But I do get this `There are no repositories in any of the folders in this directory`

**Comment by LukeGarrigan** [comment]
Are you running from a parent folder? Also what's your folder structure like, there's probably some edge cases I've missed

**Comment by justinshaw** [comment]
No, I was running from the project root (where `.git` is). The project in question is a Rails project so that's the structure

**Comment by slice-hemantsai** [comment]
i installed using nvm , but node version seen in vs code terminal but npm command is throwing error but these both commands work in CMD
