### ISSUE TITLE
Add an option to display commits from a specific date

### ISSUE THREAD

**Issue by raszi** [LukeGarrigan/git-scrum#5]
Since there are cases when I work over the weekend, and I would like to discuss the issues with the team on our standup therefore it would be great to have a feature to pass in an option to the tool to display the commit from a date instead of the last 24 hours (like the default value).

**Comment by raszi** [comment]
I have implemented the feature and I did that in 3 batches.

1. Added es-lint to help the development, and I opened a PR from it here #4
2. I refactored the code, cleaned it up a bit, and made it extensible for this feature. This work depends on #4 and the changes can be seen here: https://github.com/raszi/git-scrum/compare/feat/add-eslint...raszi:git-scrum:refactor/main
3. I've added the feature on top of the refactored branch here: https://github.com/raszi/git-scrum/compare/refactor/main...raszi:git-scrum:feat/since-option

Please let me know if you are interested in this, then I could open the rest of the PRs after each other in the same order as I listed here.

**Comment by LukeGarrigan** [comment]
Sounds good, thanks

**Comment by raszi** [comment]
I have opened the first PR here #6

**Comment by raszi** [comment]
I opened the last PR #7
